import AlarmSvg from "./assets/svgs/alarm.svg";
import AlignBottomSvg from "./assets/svgs/alignBottom.svg";
import ArrowUpRightSvg from "./assets/svgs/arrowUpRight.svg";
import ArrowUUpLeftSvg from "./assets/svgs/arrowUUpLeft.svg";
import CameraSvg from "./assets/svgs/camera.svg";
import CaretDownSvg from "./assets/svgs/caretDown.svg";
import ChartBarSvg from "./assets/svgs/chartBar.svg";
import ChartPieSliceSvg from "./assets/svgs/chartPieSlice.svg";
import ChatSvg from "./assets/svgs/chat.svg";
import ChatTeardropTextSvg from "./assets/svgs/chatTeardropText.svg";
import CheckSvg from "./assets/svgs/check.svg";
import CheckCircleSvg from "./assets/svgs/checkCircle.svg";
import CheckCircleOutlinedSvg from "./assets/svgs/checkCircleOutlined.svg";
import CircleSvg from "./assets/svgs/circle.svg";
import ClockSvg from "./assets/svgs/clock.svg";
import CloseSvg from "./assets/svgs/close.svg";
import CoinSvg from "./assets/svgs/coin.svg";
import DiamondSvg from "./assets/svgs/diamond.svg";
import DotsThreeCircleNoPadding from "./assets/svgs/dotsThreeCircleNoPadding.svg";
import EnvelopeSimpleSvg from "./assets/svgs/envelopeSimple.svg";
import EyeSvg from "./assets/svgs/eye.svg";
import EyeSlashSvg from "./assets/svgs/eyeSlash.svg";
import FaceBookSvg from "./assets/svgs/Facebook.svg";
import FireSvg from "./assets/svgs/fireSign.svg";
import ForkKnifeSvg from "./assets/svgs/forkKnife.svg";
import GearSixSvg from "./assets/svgs/gearSix.svg";
import GridMenuSvg from "./assets/svgs/gridMenu.svg";
import HandbagSvg from "./assets/svgs/handbag.svg";
import HeartStraightSvg from "./assets/svgs/heartStraight.svg";
import InstagramSvg from "./assets/svgs/Instagram.svg";
import ListSvg from "./assets/svgs/list.svg";
import ListCenterSvg from "./assets/svgs/listCenter.svg";
import LockOpenSvg from "./assets/svgs/lockOpen.svg";
import MagnifyingGlassSvg from "./assets/svgs/magnifyingGlass.svg";
import MapPinSvg from "./assets/svgs/mapPin.svg";
import MinusSvg from "./assets/svgs/minus.svg";
import MinusCircleSvg from "./assets/svgs/minusCircle.svg";
import NavigationArrowSvg from "./assets/svgs/navigationArrow.svg";
import NotePencilSvg from "./assets/svgs/notePencil.svg";
import PackageSvg from "./assets/svgs/package.svg";
import PaperPlaneTiltSvg from "./assets/svgs/paperPlaneTilt.svg";
import PathSvg from "./assets/svgs/path.svg";
import PercentCircleSvg from "./assets/svgs/percentCircle.svg";
import PhoneSvg from "./assets/svgs/Phone.svg";
import PhoneCallSvg from "./assets/svgs/phoneCall.svg";
import PlaneSvg from "./assets/svgs/plane.svg";
import PlusSvg from "./assets/svgs/plus.svg";
import PlusCircleSvg from "./assets/svgs/plusCircle.svg";
import ProhibitSvg from "./assets/svgs/prohibit.svg";
import QrCodeSvg from "./assets/svgs/qrCode.svg";
import ReceiptSvg from "./assets/svgs/receipt.svg";
import SearchOption1Svg from "./assets/svgs/searchOption1.svg";
import SearchOption2Svg from "./assets/svgs/searchOption2.svg";
import SearchOption3Svg from "./assets/svgs/searchOption3.svg";
import SearchOption4Svg from "./assets/svgs/searchOption4.svg";
import SearchOption5Svg from "./assets/svgs/searchOption5.svg";
import SearchOption6Svg from "./assets/svgs/searchOption6.svg";
import ShareSvg from "./assets/svgs/share.svg";
import ShieldCheckSvg from "./assets/svgs/ShieldCheck.svg";
import ShieldSlashSvg from "./assets/svgs/ShieldSlash.svg";
import ShirtSvg from "./assets/svgs/shirt.svg";
import ShoppingCartSvg from "./assets/svgs/shoppingCart.svg";
import SignOutSvg from "./assets/svgs/signOut.svg";
import SlidersHorizontalSvg from "./assets/svgs/SlidersHorizontal.svg";
import SmileySvg from "./assets/svgs/smiley.svg";
import SmileyNervousSvg from "./assets/svgs/smileyNervous.svg";
import StackSimpleSvg from "./assets/svgs/stackSimple.svg";
import StarSvg from "./assets/svgs/star.svg";
import StarFilledSvg from "./assets/svgs/starFilled.svg";
import StarOutlinedSvg from "./assets/svgs/starOutlined.svg";
import StorefrontSvg from "./assets/svgs/storefront.svg";
import TagSvg from "./assets/svgs/tag.svg";
import TargetSvg from "./assets/svgs/target.svg";
import TelegramSvg from "./assets/svgs/Telegram.svg";
import ThumbsUpSvg from "./assets/svgs/thumbsUp.svg";
import TikTokSvg from "./assets/svgs/TikTok.svg";
import TrashSvg from "./assets/svgs/trash.svg";
import TruckSvg from "./assets/svgs/truck.svg";
import UserSvg from "./assets/svgs/user.svg";
import UserCirclePlusSvg from "./assets/svgs/userCirclePlus.svg";
import VideoPlaySvg from "./assets/svgs/videoPlay.svg";
import VkSvg from "./assets/svgs/VK.svg";
import WalletSvg from "./assets/svgs/wallet.svg";
import WarningOctagonSvg from "./assets/svgs/warningOctagon.svg";
import WhatsAppSvg from "./assets/svgs/whatsApp.svg";

import { createIconFromSvg } from "@packages/uiKit/utils/createIconFromSvg";
// New icons
import AddSquareSvg from "./assets/svgs/add-square.svg";
import ArchiveBookSvg from "./assets/svgs/archive-book.svg";
import ArrowDownSvg from "./assets/svgs/arrowDown.svg";
import ArrowRightSvg from "./assets/svgs/arrowRight.svg";
import ArrowUpSvg from "./assets/svgs/arrowUp.svg";
import BankSvg from "./assets/svgs/bank.svg";
import BankPartnershipSvg from "./assets/svgs/bankPartnership.svg";
import BitcoinConvertSvg from "./assets/svgs/bitcoin-convert.svg";
import BlurSvg from "./assets/svgs/blur.svg";
import BookSvg from "./assets/svgs/book.svg";
import BoxSvg from "./assets/svgs/box.svg";
import BriefcaseSvg from "./assets/svgs/briefcase.svg";
import BuildingSvg from "./assets/svgs/building.svg";
import BuildingWithTreeSvg from "./assets/svgs/buildingWithTree.svg";
import CalculatorSvg from "./assets/svgs/calculator.svg";
import CalendarAddSvg from "./assets/svgs/calendar-add.svg";
import CarSvg from "./assets/svgs/car.svg";
import CaretLeftSvg from "./assets/svgs/caretLeft.svg";
import CaretRightSvg from "./assets/svgs/caretRight.svg";
import ChartSvg from "./assets/svgs/chart.svg";
import DirectRightSvg from "./assets/svgs/direct-right.svg";
import EmptyWalletChangeSvg from "./assets/svgs/empty-wallet-change.svg";
import WalletDefaultSvg from "./assets/svgs/empty-wallet-default.svg";
import ExportSvq from "./assets/svgs/export.svg";
import FavoriteChartSvg from "./assets/svgs/favorite-chart.svg";
import GlobalSvg from "./assets/svgs/global.svg";
import HomeTrendUpSvg from "./assets/svgs/home-trend-up.svg";
import JudgeSvg from "./assets/svgs/judge.svg";
import LayerSvg from "./assets/svgs/layer.svg";
import LikeStrokeSvg from "./assets/svgs/like-stroke.svg";
import LikeSvg from "./assets/svgs/like.svg";
import LogoutSvg from "./assets/svgs/logout.svg";
import MapSvg from "./assets/svgs/map.svg";
import MessageNotificationSvg from "./assets/svgs/messageNotification.svg";
import MoneysSvg from "./assets/svgs/moneys.svg";
import MonitorMobileSvg from "./assets/svgs/monitor-mobile.svg";
import NoteFavoriteSvg from "./assets/svgs/noteFavorite.svg";
import NotificationStatusSvg from "./assets/svgs/notification-status.svg";
import PlayRoundedSvg from "./assets/svgs/play-rounded.svg";
import RussiaSvg from "./assets/svgs/russia.svg";
import SecurityUserSvg from "./assets/svgs/security-user.svg";
import ShopAddSvg from "./assets/svgs/shopAdd.svg";
import ShoppingCart1Svg from "./assets/svgs/shopping-cart.svg";
import SmartphoneSvg from "./assets/svgs/smartphone.svg";
import StatusUpSvg from "./assets/svgs/status-up.svg";
import UserCircleAddSvg from "./assets/svgs/user-circle-add.svg";
import WalletAddSvg from "./assets/svgs/wallet-add.svg";
import WalletCheckSvg from "./assets/svgs/wallet-check.svg";

import CardsSwitchSvg from "./assets/svgs/cards-switch.svg";
import MinusSquareSvg from "./assets/svgs/minus-square.svg";
import RepeatMusicSvg from "./assets/svgs/repeate-music.svg";

import CardTickSvg from "./assets/svgs/card-tick.svg";
import CloseSquareSvg from "./assets/svgs/close-square.svg";
import DocumentTextIconSvg from "./assets/svgs/document-text.svg";
import EmptyWalletAddSvg from "./assets/svgs/empty-wallet-add.svg";
import MobNavBankSvg from "./assets/svgs/mobNavBank.svg";
import MobNavLayerSvg from "./assets/svgs/mobNavLayer.svg";
import MobNavMoneysSvg from "./assets/svgs/mobNavMoneys.svg";
import MobNavStatusUpSvg from "./assets/svgs/mobNavStatus-up.svg";
import MobNavWalletAddSvg from "./assets/svgs/mobNavWallet-add.svg";

import CardAddSvg from "./assets/svgs/card-add.svg";
import DiscountShapeSvg from "./assets/svgs/discount-shape.svg";
import MoneyChangeSvg from "./assets/svgs/money-change.svg";
import WalletMoneySvg from "./assets/svgs/wallet-money.svg";

import ArrowSquareLeftSvg from "./assets/svgs/arrow-square-left.svg";
import CallCallingSvg from "./assets/svgs/call-calling.svg";
import EmptyWalletTickSvg from "./assets/svgs/empty-wallet-tick.svg";
import KeySvg from "./assets/svgs/key.svg";
import ProgrammingArrowSvg from "./assets/svgs/programming-arrow.svg";
import UnlockSvg from "./assets/svgs/unlock.svg";
import UserCircleAddRoundSvg from "./assets/svgs/user-circle-add.svg";

export const UnlockIcon = createIconFromSvg(UnlockSvg);
export const KeyIcon = createIconFromSvg(KeySvg);
export const ArrowSquareLeftIcon = createIconFromSvg(ArrowSquareLeftSvg);

export const CallCallingIcon = createIconFromSvg(CallCallingSvg);
export const EmptyWalletTickIcon = createIconFromSvg(EmptyWalletTickSvg);
export const ProgrammingArrowIcon = createIconFromSvg(ProgrammingArrowSvg);
export const UserCircleAddRoundIcon = createIconFromSvg(UserCircleAddRoundSvg);

// mobileNav Icons
export const MobNavLayer = createIconFromSvg(MobNavLayerSvg);
export const MobNavBank = createIconFromSvg(MobNavBankSvg);
export const MobNavMoneys = createIconFromSvg(MobNavMoneysSvg);
export const MobNavStatusUp = createIconFromSvg(MobNavStatusUpSvg);
export const MobNavWalletAdd = createIconFromSvg(MobNavWalletAddSvg);

// new icon Components
export const WalletMoneyIcon = createIconFromSvg(WalletMoneySvg);
export const MoneyChangeIcon = createIconFromSvg(MoneyChangeSvg);
export const DiscountShapeIcon = createIconFromSvg(DiscountShapeSvg);
export const CardAddIcon = createIconFromSvg(CardAddSvg);

export const CloseSquareIcon = createIconFromSvg(CloseSquareSvg);
export const DocumentTextIcon = createIconFromSvg(DocumentTextIconSvg);
export const CardTickIcon = createIconFromSvg(CardTickSvg);
export const EmptyWalletAddIcon = createIconFromSvg(EmptyWalletAddSvg);

export const CardsSwitchIcon = createIconFromSvg(CardsSwitchSvg);
export const MinusSquareIcon = createIconFromSvg(MinusSquareSvg);
export const RepeatMusicIcon = createIconFromSvg(RepeatMusicSvg);

export const ArchiveBookIcon = createIconFromSvg(ArchiveBookSvg);
export const AddSquareIcon = createIconFromSvg(AddSquareSvg);
export const ExportIcon = createIconFromSvg(ExportSvq);
export const WalletCheckIcon = createIconFromSvg(WalletCheckSvg);
export const MoneysIcon = createIconFromSvg(MoneysSvg);
export const CalendarAddIcon = createIconFromSvg(CalendarAddSvg);
export const LikeStrokeIcon = createIconFromSvg(LikeStrokeSvg);
export const ShoppingCart1Icon = createIconFromSvg(ShoppingCart1Svg);
export const JudgeIcon = createIconFromSvg(JudgeSvg);
export const BoxIcon = createIconFromSvg(BoxSvg);
export const BankPartnershipIcon = createIconFromSvg(BankPartnershipSvg);
export const GlobalIcon = createIconFromSvg(GlobalSvg);
export const UserCircleAddIcon = createIconFromSvg(UserCircleAddSvg);
export const WalletDefaultIcon = createIconFromSvg(WalletDefaultSvg);
export const PlayRoundedIcon = createIconFromSvg(PlayRoundedSvg);
export const DirectRightIcon = createIconFromSvg(DirectRightSvg);
export const CarIcon = createIconFromSvg(CarSvg);
export const WalletAddIcon = createIconFromSvg(WalletAddSvg);
export const EmptyWalletChangeIcon = createIconFromSvg(EmptyWalletChangeSvg);
export const BuildingWithTreeIcon = createIconFromSvg(BuildingWithTreeSvg);
export const MonitorMobileIcon = createIconFromSvg(MonitorMobileSvg);
export const CalculatorIcon = createIconFromSvg(CalculatorSvg);
export const StatusUpIcon = createIconFromSvg(StatusUpSvg);
export const ShopAddIcon = createIconFromSvg(ShopAddSvg);
export const MapIcon = createIconFromSvg(MapSvg);
export const SmartphoneIcon = createIconFromSvg(SmartphoneSvg);
export const NoteFavoriteIcon = createIconFromSvg(NoteFavoriteSvg);
export const MessageNotificationIcon = createIconFromSvg(
  MessageNotificationSvg
);
export const BuildingIcon = createIconFromSvg(BuildingSvg);
export const ArrowDownIcon = createIconFromSvg(ArrowDownSvg);
export const ArrowUpIcon = createIconFromSvg(ArrowUpSvg);
export const ArrowRightIcon = createIconFromSvg(ArrowRightSvg);
export const LikeIcon = createIconFromSvg(LikeSvg);
export const BankIcon = createIconFromSvg(BankSvg);
export const BlurIcon = createIconFromSvg(BlurSvg);
export const RussiaIcon = createIconFromSvg(RussiaSvg);
export const BitcoinConvertIcon = createIconFromSvg(BitcoinConvertSvg);
export const BriefcaseIcon = createIconFromSvg(BriefcaseSvg);
export const FavoriteChartIcon = createIconFromSvg(FavoriteChartSvg);
export const HomeTrendUpIcon = createIconFromSvg(HomeTrendUpSvg);
export const NotificationStatusIcon = createIconFromSvg(NotificationStatusSvg);
//
export const BookIcon = createIconFromSvg(BookSvg);
export const ChartIcon = createIconFromSvg(ChartSvg);
export const LayerIcon = createIconFromSvg(LayerSvg);
export const SecurityUserIcon = createIconFromSvg(SecurityUserSvg);
export const LogoutIcon = createIconFromSvg(LogoutSvg);
/* 



*/
// old icon Components
export const AlarmIcon = createIconFromSvg(AlarmSvg);
export const NavigationArrowIcon = createIconFromSvg(NavigationArrowSvg);
export const GridMenuIcon = createIconFromSvg(GridMenuSvg);
export const ListIcon = createIconFromSvg(ListSvg);
export const ListCenterIcon = createIconFromSvg(ListCenterSvg);
export const CaretDownIcon = createIconFromSvg(CaretDownSvg);
export const MagnifyingGlassIcon = createIconFromSvg(MagnifyingGlassSvg);
export const HeartStraightIcon = createIconFromSvg(HeartStraightSvg);
export const AlignBottomIcon = createIconFromSvg(AlignBottomSvg);
export const UserIcon = createIconFromSvg(UserSvg);
export const ShoppingCartIcon = createIconFromSvg(ShoppingCartSvg);
export const PercentCircleIcon = createIconFromSvg(PercentCircleSvg);
export const ShirtIcon = createIconFromSvg(ShirtSvg);
export const CaretRightIcon = createIconFromSvg(CaretRightSvg);
export const CloseIcon = createIconFromSvg(CloseSvg);
export const CaretLeftIcon = createIconFromSvg(CaretLeftSvg);
export const ThumbsUpIcon = createIconFromSvg(ThumbsUpSvg);
export const CoinIcon = createIconFromSvg(CoinSvg);
export const MapPinIcon = createIconFromSvg(MapPinSvg);
export const TruckIcon = createIconFromSvg(TruckSvg);
export const TagIcon = createIconFromSvg(TagSvg);
export const ArrowUUpLeftIcon = createIconFromSvg(ArrowUUpLeftSvg);
export const HandbagIcon = createIconFromSvg(HandbagSvg);
export const ChatTeardropTextIcon = createIconFromSvg(ChatTeardropTextSvg);
export const WalletIcon = createIconFromSvg(WalletSvg);
export const PhoneCallIcon = createIconFromSvg(PhoneCallSvg);
export const CheckIcon = createIconFromSvg(CheckSvg);
export const PlusIcon = createIconFromSvg(PlusSvg);
export const MinusIcon = createIconFromSvg(MinusSvg);
export const PlaneIcon = createIconFromSvg(PlaneSvg);
export const StarIcon = createIconFromSvg(StarSvg);
export const ShareIcon = createIconFromSvg(ShareSvg);
export const ChatIcon = createIconFromSvg(ChatSvg);
export const TargetIcon = createIconFromSvg(TargetSvg);
export const FireIcon = createIconFromSvg(FireSvg);
export const LockOpenIcon = createIconFromSvg(LockOpenSvg);
export const DotsThreeCirclesNoPadding = createIconFromSvg(
  DotsThreeCircleNoPadding
);
export const StarFilledIcon = createIconFromSvg(StarFilledSvg);
export const StarOutlinedIcon = createIconFromSvg(StarOutlinedSvg);
export const DiamondIcon = createIconFromSvg(DiamondSvg);
export const PlusCircleIcon = createIconFromSvg(PlusCircleSvg);
export const MinusCircleIcon = createIconFromSvg(MinusCircleSvg);
export const QrCodeIcon = createIconFromSvg(QrCodeSvg);
export const ProhibitIcon = createIconFromSvg(ProhibitSvg);
export const CheckCircleIcon = createIconFromSvg(CheckCircleSvg);
export const CheckCircleOutlinedIcon = createIconFromSvg(
  CheckCircleOutlinedSvg
);
export const NotePencilIcon = createIconFromSvg(NotePencilSvg);
export const EyeIcon = createIconFromSvg(EyeSvg);
export const UserCirclePlusIcon = createIconFromSvg(UserCirclePlusSvg);
export const SmileyNervousIcon = createIconFromSvg(SmileyNervousSvg);
export const ChartPieSliceIcon = createIconFromSvg(ChartPieSliceSvg);
export const SmileyIcon = createIconFromSvg(SmileySvg);
export const ReceiptIcon = createIconFromSvg(ReceiptSvg);
export const PaperPlaneTiltIcon = createIconFromSvg(PaperPlaneTiltSvg);
export const EyeSlashIcon = createIconFromSvg(EyeSlashSvg);
export const TrashIcon = createIconFromSvg(TrashSvg);
export const ForkKnifeIcon = createIconFromSvg(ForkKnifeSvg);
export const GearSixIcon = createIconFromSvg(GearSixSvg);
export const SignOutIcon = createIconFromSvg(SignOutSvg);
export const PlayIcon = createIconFromSvg(VideoPlaySvg);
export const CircleIcon = createIconFromSvg(CircleSvg);
export const StackSimpleIcon = createIconFromSvg(StackSimpleSvg);
export const StorefrontIcon = createIconFromSvg(StorefrontSvg);
export const ChartBarIcon = createIconFromSvg(ChartBarSvg);
export const PackageIcon = createIconFromSvg(PackageSvg);
export const EnvelopeSimpleIcon = createIconFromSvg(EnvelopeSimpleSvg);
export const ClockIcon = createIconFromSvg(ClockSvg);
export const PathIcon = createIconFromSvg(PathSvg);
export const WarningOctagonIcon = createIconFromSvg(WarningOctagonSvg);

export const FaceBookIcon = createIconFromSvg(FaceBookSvg);
export const InstagramIcon = createIconFromSvg(InstagramSvg);
export const TelegramIcon = createIconFromSvg(TelegramSvg);
export const VkIcon = createIconFromSvg(VkSvg);
export const WhatsAppIcon = createIconFromSvg(WhatsAppSvg);
export const TikTokIcon = createIconFromSvg(TikTokSvg);
export const ShieldCheckIcon = createIconFromSvg(ShieldCheckSvg);
export const ShieldSlashIcon = createIconFromSvg(ShieldSlashSvg);
export const PhoneIcon = createIconFromSvg(PhoneSvg);
export const SlidersHorizontalIcon = createIconFromSvg(SlidersHorizontalSvg);
export const CameraIcon = createIconFromSvg(CameraSvg);
export const ArrowUpRightIcon = createIconFromSvg(ArrowUpRightSvg);

export const SearchOptionIcon1 = createIconFromSvg(SearchOption1Svg);
export const SearchOptionIcon2 = createIconFromSvg(SearchOption2Svg);
export const SearchOptionIcon3 = createIconFromSvg(SearchOption3Svg);
export const SearchOptionIcon4 = createIconFromSvg(SearchOption4Svg);
export const SearchOptionIcon5 = createIconFromSvg(SearchOption5Svg);
export const SearchOptionIcon6 = createIconFromSvg(SearchOption6Svg);
